### ISSUE TITLE
Media query conditions should be responsive

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/only-show#5]
Is it enough to watch for resize events? That seems like a good start at least.

The other approach here would be to apply CSS queries as CSS, which will respond dynamically without any other JS. We might still want a way to keep the 'hidden' attribute up to date?

@jamesnw curious if you have thoughts on that?

**Comment by jamesnw** [comment]
I think we should be able to listen for change events on the matchMedia query- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Testing_media_queries. That way we can handle things like changing from dark theme to light theme. 

Adding it to the CSS would work as well, but I'm not thinking of an easy way of keeping the `hidden` attribute up to date, which would make the `has-media` match behave differently than the others.
